backend:
  name: git-gateway
  branch: _content
publish_mode: editorial_workflow
media_folder: "src/media"
public_folder: "/media"
collections:
  - name: "globals"
    label: "Globals"
    files:
      - name: "site_data"
        label: "Site Data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
  - name: "key_pages"
    label: "Key Pages"
    files:
      - name: "home"
        label: "Home"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base"}
          - {label: "Title", name: "pageTitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
